-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.hubspot_commissions_obj (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hubspot_id text NOT NULL UNIQUE,
  object_type_id text DEFAULT '2-45314755'::text,
  name text,
  deal_id text,
  owner_id text,
  commission_amount numeric,
  commission_percentage numeric,
  commission_type text,
  payment_status text,
  payment_date date,
  associated_deal_id text,
  associated_contact_id text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  raw_properties jsonb,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_commissions_obj_pkey PRIMARY KEY (id),
  CONSTRAINT fk_commissions_owner FOREIGN KEY (owner_id) REFERENCES public.hubspot_owners(hubspot_id)
);
CREATE TABLE public.hubspot_contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hubspot_id text NOT NULL UNIQUE,
  email text,
  first_name text,
  last_name text,
  phone text,
  mobile_phone text,
  job_title text,
  company_id text,
  lifecycle_stage text,
  lead_status text,
  owner_id text,
  city text,
  state text,
  country text,
  postal_code text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_contacts_owner FOREIGN KEY (owner_id) REFERENCES public.hubspot_owners(hubspot_id)
);
CREATE TABLE public.hubspot_deals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hubspot_id text NOT NULL UNIQUE,
  deal_name text,
  amount numeric,
  currency text DEFAULT 'BRL'::text,
  close_date date,
  create_date timestamp with time zone,
  pipeline_id text,
  pipeline_stage_id text,
  deal_stage text,
  deal_type text,
  owner_id text,
  contact_id text,
  company_id text,
  probability numeric,
  forecast_category text,
  next_step text,
  description text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  raw_data jsonb,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_deals_pkey PRIMARY KEY (id),
  CONSTRAINT fk_deals_owner FOREIGN KEY (owner_id) REFERENCES public.hubspot_owners(hubspot_id),
  CONSTRAINT fk_deals_contact FOREIGN KEY (contact_id) REFERENCES public.hubspot_contacts(hubspot_id),
  CONSTRAINT fk_deals_pipeline FOREIGN KEY (pipeline_id) REFERENCES public.hubspot_pipelines(hubspot_id),
  CONSTRAINT fk_deals_stage FOREIGN KEY (pipeline_stage_id) REFERENCES public.hubspot_pipeline_stages(stage_id)
);
CREATE TABLE public.hubspot_line_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hubspot_id text NOT NULL UNIQUE,
  deal_id text,
  product_id text,
  name text,
  sku text,
  quantity numeric,
  unit_price numeric,
  amount numeric,
  discount numeric,
  discount_percentage numeric,
  currency text DEFAULT 'BRL'::text,
  description text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_lineitems_deal FOREIGN KEY (deal_id) REFERENCES public.hubspot_deals(hubspot_id)
);
CREATE TABLE public.hubspot_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hubspot_id text NOT NULL UNIQUE,
  email text,
  first_name text,
  last_name text,
  user_id text,
  team_id text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_owners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hubspot_pipeline_stages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  stage_id text NOT NULL UNIQUE,
  pipeline_id text,
  label text,
  display_order integer,
  probability numeric,
  is_closed boolean DEFAULT false,
  is_won boolean DEFAULT false,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_pipeline_stages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_stages_pipeline FOREIGN KEY (pipeline_id) REFERENCES public.hubspot_pipelines(hubspot_id)
);
CREATE TABLE public.hubspot_pipelines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hubspot_id text NOT NULL UNIQUE,
  label text,
  display_order integer,
  object_type text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived boolean DEFAULT false,
  _extracted_at timestamp with time zone NOT NULL DEFAULT now(),
  _source_system text NOT NULL DEFAULT 'HubSpot'::text,
  CONSTRAINT hubspot_pipelines_pkey PRIMARY KEY (id)
);